# Generated by Django 5.1.5 on 2025-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=50, unique=True)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_weight', models.FloatField()),
                ('product_color', models.CharField(max_length=100)),
                ('product_size', models.CharField(max_length=50)),
                ('product_supplier', models.CharField(max_length=300)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
